language: node_js
node_js:
  - "10"
dist: trusty
before_install:
  - sudo apt-get install -y jq
install:
  - npm i
script:
  - chmod +x ./run.sh
  - ./run.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target_branch: gh-pages
  email: $GITHUB_EMAIL
  name: $GITHUB_USER
  local-dir: dist
  on:
    branch: master
