language: node_js
node_js:
  - "10"
sudo: enabled
dist: xenial

install:
  - sudo sed -i 's|http://us-east-1.ec2.archive.ubuntu.com|https://mirrors.speedtests.ml|g' /etc/apt/sources.list
  - sudo sed -i 's|http://security.ubuntu.com|https://mirrors.speedtests.ml|g' /etc/apt/sources.list
  - sudo apt update
  - sudo apt install -y jq
script:
  - chmod +x ./run.sh
  - ./run.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target_branch: gh-pages
  email: $GITHUB_EMAIL
  name: $GITHUB_USER
  local-dir: dist
  on:
    branch: master
cache:
  directories:
    - node_modules
